### ISSUE TITLE
Milestone for 1.0

### ISSUE THREAD

**Issue by ragingwind** [react-photonkit/react-photonkit#28]
Gathering what should be improved in 1.0
## Core
- [x] Migrate to use ES6
- [ ] ~~Change build system into ? or Make it more simply [delayed]~~
- [ ] ~~Using AVA [delayed]~~
- [x] Using xo
### TabGroup
- [ ] `tab-item-fixed`
- [ ] close a tab
### ListGroup
- [ ] `list-group-header`

**Comment by ragingwind** [comment]
1. Improve documents
2. Updated example site
